### ISSUE TITLE
Expo 49 and webpack config

### ISSUE THREAD

**Issue by lakardion** [kanzitelli/rn-bounceable#7]
Hello! I love this component.

Is there a chance we would get an update so that it doesn't use webpack config anymore (if there's a way)? 

We wanted to use new [Expo 49's absolute paths](https://docs.expo.dev/guides/typescript/#absolute-imports) but doesn't work if we're using `@expo/webpack-config` for this component

**Comment by lakardion** [comment]
Furthermore, `@expo/webpack-config` is already deprecated so the Expo team is pushing for a migration out of this package.

https://docs.expo.dev/router/migrate/from-expo-webpack/

**Comment by kanzitelli** [comment]
Hi @lakardion!

Thanks for the update. Since they've deprecated the package, what happens if you install `rn-bounceable` and use it without `@expo/webpack-config`?

**Comment by lakardion** [comment]
Thanks! Seems to keep working so it looks that it doesn't need webpack config anymore!
